### ISSUE TITLE
.

### ISSUE THREAD

**Issue by infix123** [joeattardi/coffee-shop-starter#14]

**Comment by joeattardi** [comment]
If you are looking for help that's a funny way to ask. 

"Nothing working" makes it impossible for me to help you. Is there a particular issue or error you are facing?

**Comment by infix123** [comment]
you can read the message again, it was specific to config.yml file.

**Comment by joeattardi** [comment]
Again, "nothing works" tells me nothing. 

Are you getting an error from your config.yml? Error message anywhere? I can't help you if you don't give me details. 

You might benefit from reading this: https://github.com/selfteaching/How-To-Ask-Questions-The-Smart-Way/blob/master/How-To-Ask-Questions-The-Smart-Way.md

Your attitude sucks but I'll try to help. I took a look at your coffee-shop repository and your config.yml file is full of issues. Whitespace problems, incorrect format. 

This might be helpful: https://circleci.com/blog/what-is-yaml-a-beginner-s-guide/

Also here is my config.yml from the finished project: 

https://github.com/joeattardi/coffee-shop/blob/master/static/admin/config.yml

Before you call me out and criticize the book, make sure your syntax is correct!.

**Comment by infix123** [comment]
your book sucks

**Comment by joeattardi** [comment]
I'm not sure what your goal is here.

If you want help, you can ask like an adult or you can go figure it out by yourself. 

If you hate the book, then leave a review and stop harassing me.

**Comment by joeattardi** [comment]
Come back when you learn how to be respectful of others' work.
